import type { Metadata } from "next";
import "@/app/[locale]/globals.css";
import Navbar from "../../ui/Navbar";
import { NextIntlClientProvider } from "next-intl";
import { useTranslations } from "next-intl";
import Footer from "../../ui/Footer";
import { Montserrat } from "@next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
  params: { locale: string };
}

interface NavbarProps {
  inicio: string;

  paquetes: string;

  blog: string;

  nosotros: string;

  contacto: string;

  isesion: string;

  registro: string;

  soporte: string;

  preguntas: string;
}

const montserrat = Montserrat({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], // todos los pesos
  subsets: ["latin"],
});

export default function LocaleLayout({
  children,
  params: { locale },
}: RootLayoutProps) {
  const t = useTranslations();
  return (
    <html lang={locale} className="">
      <body className={montserrat.className}>
        <Navbar
          inicio={t("navbar.inicio")}
          paquetes={t("navbar.paquetes")}
          blog={t("navbar.blog")}
          nosotros={t("navbar.nosotros")}
          contacto={t("navbar.contacto")}
          isesion={t("navbar.isesion")}
          registro={t("navbar.registro")}
          soporte={t("navbar.soporte")}
          preguntas={t("navbar.preguntas")}
        />
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
