import type { Metadata } from "next";
import "./globals.css";
import Navbar from "../ui/Navbar";
import Footer from "../ui/Footer";
import { NextIntlClientProvider } from "next-intl";
import { Montserrat } from "@next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
  params: { locale: string };
}

const montserrat = Montserrat({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], // todos los pesos
  subsets: ["latin"],
});

export default async function LocaleLayout({
  children,
  params: { locale },
}: RootLayoutProps) {
  // Importa mensajes de traducción dinámicamente según el idioma
  const messages = (await import(`/messages/${locale}.json`)).default;

  return (
    <html lang={locale} className="">
      <body className={montserrat.className}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
